apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: konga
  name: konga
  namespace: kong-gateway
spec:
  ports:
    - port: 1337
      protocol: TCP
      targetPort: http
  selector:
    app: konga
  type: ClusterIP
