apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: prompty-dev-gateway
    argocd.argoproj.io/managed-by: Helm
    app.kubernetes.io/name: kong
    app.kubernetes.io/version: '2.8'
    argocd.argoproj.io/instance: prompty-dev-gateway
    helm.sh/chart: kong-2.12.0
  name: prompty-dev-gateway
  namespace: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: prompty-dev-gateway
      app.kubernetes.io/name: kong
  template:
    metadata:
      labels:
        app: prompty-dev-gateway-kong
        app.kubernetes.io/component: app
        app.kubernetes.io/instance: prompty-dev-gateway
        argocd.argoproj.io/managed-by: Helm
        app.kubernetes.io/name: kong
        app.kubernetes.io/version: '2.8'
        helm.sh/chart: kong-2.12.0
        version: '2.8'
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      initContainers:
        - name: wait-for-db
          image: kong/kong-gateway:latest
          args:
            - /bin/sh
            - '-c'
            - 'kong migrations bootstrap && kong migrations up && kong migrations finish'
          imagePullPolicy: IfNotPresent
          env:
            # DATABASE CONFIG
            - name: KONG_DATABASE
              value: postgres

            - name: KONG_PG_HOST
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_HOST
            - name: KONG_PG_PORT
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_PORT
            - name: KONG_PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_DATABASE
            - name: KONG_PG_USER
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_USER
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_PASSWORD
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG 
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            # KONG PROXY LISTEN
            - name: KONG_PROXY_LISTEN
              value: '0.0.0.0:8000'
            # KONG ADMIN LISTEN
            - name: KONG_ADMIN_LISTEN
              value: '0.0.0.0:8001'  
            - name: KONG_STATUS_LISTEN
              value: '0.0.0.0:8100'
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 0Gi

        
      containers:
        - name: prompty-dev-gateway
          image: kong/kong-gateway:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - kong
                  - quit
                  - '--wait=15'
          ports:
            - containerPort: 8000
              name: proxy
              protocal: TCP
            - containerPort: 8001
              name: admin
              protocal: TCP
            - containerPort: 8100
              name: status
              protocal: TCP
            - containerPort: 8443
              name: proxy-https
              protocal: TCP
            - containerPort: 8444
              name: admin-https
              protocal: TCP
          env:
            # DATABASE CONFIG
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG 
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_PG_HOST
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_HOST
            - name: KONG_PG_PORT
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_PORT
            - name: KONG_PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_DATABASE
            - name: KONG_PG_USER
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_USER
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  prompty-dev-gateway-kong
                  key: KONG_PG_PASSWORD
            - name: KONG_LUA_PACKAGE_PATH
              value: /usr/local/share/lua/5.1/?.lua
            
            # KONG PROXY LISTEN
            - name: KONG_PROXY_LISTEN
              value: '0.0.0.0:8000'
            # KONG ADMIN LISTEN
            - name: KONG_ADMIN_LISTEN
              value: '0.0.0.0:8001'  
            - name: KONG_STATUS_LISTEN
              value: '0.0.0.0:8100'
          resources:
            requests:
              cpu: 100m
              memory: 0Gi
            limits:
              cpu: 1
              memory: 2Gi
          # TODO: Add liveness and readiness after create health check
          livenessProbe:
            httpGet:
              path: /status
              port: status
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /status
              port: status
              scheme: HTTP
            initialDelaySeconds: 50
            timeoutSeconds: 5
            periodSeconds: 23
            successThreshold: 1
            failureThreshold: 3